### PR TITLE
Possible Solution

### PR DESCRIPTION
**Pull request by GitGangGuy**

### CODE REVIEW

**Comment by EricPKerr** [comment]
@GitGangGuy thanks for the PR.

I think everything looks good - any comment on the switch from npm to yarn?  This would presume that yarn is installed globally, which at this point is safe.  Was just checking.

**Comment by GitGangGuy** [comment]
I just personally use [yarn](https://yarnpkg.com/lang/en/) as a package manager instead npm, because it has proven itself to work better when collaborating (that's why so many large open source repos use yarn), it uses emojis in the console :wink:, and I have to type less (`yarn` instead of `npm i`, `yarn [script-name]` instead of `npm run [script-name]`). Of course, if you prefer npm, you can just switch it before merging.

**Comment by GitGangGuy** [comment]
Also, the lockfile (`yarn.lock`) should be commited, but I excluded it from commits in the `.gitignore` file because I'm lazy. Should remove line 7 of that file.

**Comment by EricPKerr** [comment]
Let's leave it as `npm` for the time being - happy to merge afterwords.  Thanks again

**Comment by GitGangGuy** [comment]
From what I see, you should be able to commit to the master branch of my fork - modify it to your needs ;)

**Comment by EricPKerr** [comment]
I pulled this down and wasn't able to get the postcss to work properly between dev/prod.  There's still the postcss and cssnano part mentioned in rollup.config.js (vs just using postcss.config.js everywhere)

**Comment by jadbox** [comment]
What does this PR do?

**Comment by GitGangGuy** [comment]
> What does this PR do?

https://github.com/EricPKerr/sapper-tailwindcss/issues/5

**Comment by Suyashtnt** [comment]
I would like to try this in my project, how can I clone this version?

**Comment by GitGangGuy** [comment]
I've lost track of what I did here, today I'm just using a tailwind component in my layout file so I can all process it through `svelte-preprocess`, without a need for any additional rollup plugins. Closing.

**Pull request closed without merging**
